# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - modules/*

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7.5'

steps:
- checkout: self
  persistCredentials: true
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: BatchScript@1
  inputs:
    filename: RunSconsRelease.bat
  displayName: 'Build Editor'

- script: |
    git config --global user.email "ArgumentDevOps@github.com"
    git config --global user.name "Argument DevOps"
  displayName: 'Setup git config'

- task: BatchScript@1
  inputs:
    filename: CommitEditorStable.bat
  displayName: 'Submit Editor'
